name: "PyAction: One-stop Python linter"
description: "One-stop, zero-configuration GitHub Action for linting and enforcing style in Python projects."
inputs:
  python-root-list:
    description: "A list of all paths to test"
    required: false
    default: "./**/*.py"
  use-pylint:
    description: "Use Pylint"
    required: false
    default: true
  use-pycodestyle:
    description: "Use pycodestyle"
    required: false
    default: true
  use-flake8:
    description: "Use Flake8"
    required: false
    default: true
  use-black:
    description: "Use Black"
    required: false
    default: true
  use-mypy:
    description: "Use mypy"
    required: false
    default: true
  use-isort:
    description: "Use isort"
    required: false
    default: true
  use-vulture:
    description: "Use vulture"
    required: false
    default: true
  use-pydocstyle:
    description: "Use pydocstyle"
    required: false
    default: true
  extra-pylint-options:
    description: "Extra options: pylint $(extra-pylint-options) $(python-root-list)"
    required: false
    default: ""
  extra-pycodestyle-options:
    description: "Extra options: pycodestyle $(extra-pycodestyle-options) $(python-root-list)"
    required: false
    default: ""
  extra-flake8-options:
    description: "Extra options: flake8 $(extra-flake8-options) $(python-root-list)"
    required: false
    default: ""
  extra-black-options:
    description: "Extra options: black --check $(extra-black-options) $(python-root-list)"
    required: false
    default: ""
  extra-mypy-options:
    description: "Extra options: mypy $(extra-mypy-options) $(python-root-list)"
    required: false
    default: ""
  extra-isort-options:
    description: "Extra options: isort -rc $(extra-isort-options) $(python-root-list) -c --diff "
    required: false
    default: ""
  extra-vulture-options:
    description: "Extra options: vulture $(extra-vulture-options) $(python-root-list)"
    required: false
    default: ""
  extra-pydocstyle-options:
    description: "Extra options: pydocstyle $(extra-pydocstyle-options) $(python-root-list)"
    required: false
    default: ""

runs:
  using: "composite"
  steps: 
    - run: |
        conda --version
        conda env create -f {{ github.action_path }}/entrypoint.sh --yes
        conda env list
        conda activate lint_env
      shell: bash
      name: Install lintners
    - run: |
        python --version
        pip freeze
        pip install wheel
        pip install setuptools
        pip install pycodestyle
        pip install pydocstyle
        pip install pylint
        pip install mypy
        pip install black
        pip install flake8
        pip install vulture
        pip install isort
      shell: bash
      name: Install lintners
    - run: ${{ github.action_path }}/entrypoint.sh ${{ inputs.python-root-list }} ${{ inputs.use-pylint }} ${{ inputs.use-pycodestyle }} ${{ inputs.use-flake8 }} ${{ inputs.use-black }} ${{ inputs.use-mypy }} ${{ inputs.use-isort }} ${{ inputs.use-vulture }} ${{ inputs.extra-pylint-options }} ${{ inputs.extra-pycodestyle-options }} ${{ inputs.extra-flake8-options }} ${{ inputs.extra-black-options }} ${{ inputs.extra-mypy-options }} ${{ inputs.extra-isort-options }} ${{ inputs.extra-vulture-options }}
      shell: bash
      name: Lint
